version: "3"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.0"
        environment:
#            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
            
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        volumes:
            - ./elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - elk

    kibana:
        image: "docker.elastic.co/kibana/kibana:7.10.0"
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        networks:
            - elk
        depends_on:
            - elasticsearch

    filebeat:
        image: "docker.elastic.co/beats/filebeat:7.10.0"
        user: root
        links:
            - elasticsearch
            - kibana
        networks:
          - elk
       
        configs:
          - source: fb_config
            target: /usr/share/filebeat/filebeat.yml
            
        volumes:
            - ./filebeat:/usr/share/filebeat/data
            - /var/lib/docker:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
        environment:
            - ELASTICSEARCH_HOST=http://40.91.203.79:9200/
            - KIBANA_HOST=http://40.91.203.79:5601/
 
networks:
  elk:
    driver: bridge
     
configs:
  fb_config:
    file: /home/azureuser/ELK-Repo/ELK/filebeat/config/filebeat.yml           

volumes:
    elasticsearch_data:
    
volumes:
    filebeat: